sudo: required
services:
  - docker
  
before_install:
  - docker build -t mmickaels/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mmickaels/react-test npm test
  
after_success:
  - docker build -t mmickaels/multi-client ./client
  - docker build -t mmickaels/multi-nginx ./nginx
  - docker build -t mmickaels/multi-server ./server
  - docker build -t mmickaels/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mmickaels/multi-client
  - docker push mmickaels/multi-nginx
  - docker push mmickaels/multi-server
  - docker push mmickaels/multi-worker
  - docker push mmickaels/react-test

deploy: 
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react" 
  env: "DockerMulti-env"
  bucket_name: "elasticbeanstalk-us-east-1-868162420466"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
